.g not found, maybe you meant:

ARGF#getbyte
ARGF#getc
ARGF#gets
Addrinfo#getnameinfo
Addrinfo::getaddrinfo
BasicSocket#getpeereid
BasicSocket#getpeername
BasicSocket#getsockname
BasicSocket#getsockopt
CSV#gets
CSV::generate
CSV::generate_line
DEBUGGER__#get_thread
Date#gregorian
Date#gregorian?
Date::gregorian_leap?
Dir::getwd
Dir::glob
Enumerable#grep
Enumerable#group_by
Enumerator::Lazy#grep
Etc::getgrent
Etc::getgrgid
Etc::getgrnam
Etc::getlogin
Etc::getpwent
Etc::getpwnam
Etc::getpwuid
Etc::group
File::Stat#gid
File::Stat#grpowned?
File::grpowned?
FileTest#grpowned?
FileUtils#getwd
FileUtils::getwd
GC#garbage_collect
Gem::BasicSpecification#gem_dir
Gem::BasicSpecification#gems_dir
Gem::Command#get_all_gem_names
Gem::Command#get_all_gem_names_and_versions
Gem::Command#get_one_gem_name
Gem::Command#get_one_optional_argument
Gem::Commands::CleanupCommand#get_candidate_gems
Gem::Commands::CleanupCommand#get_gems_to_cleanup
Gem::Commands::CleanupCommand#get_primary_gems
Gem::Commands::ContentsCommand#gem_contents
Gem::Commands::SetupCommand#generate_default_dirs
Gem::Commands::UnpackCommand#get_metadata
Gem::Commands::UnpackCommand#get_path
Gem::Commands::YankCommand#get_platform_from_requirements
Gem::Commands::YankCommand#get_version_from_requirements
Gem::Doctor#gem_repository?
Gem::Indexer#gem_file_list
Gem::Indexer#generate_index
Gem::Indexer#gzip
Gem::Installer#gem
Gem::Installer#gem_dir
Gem::Installer#gem_home
Gem::Installer#generate_bin
Gem::Installer#generate_bin_script
Gem::Installer#generate_bin_symlink
Gem::Installer#generate_windows_script
Gem::Package#gzip_to
Gem::Package::TarReader::Entry#getc
Gem::PackageTask#gem_spec
Gem::Request#get_no_proxy_from_env
Gem::Request#get_proxy_from_env
Gem::RequestSet#gem
Gem::RequestSet::GemDependencyAPI#gem
Gem::RequestSet::GemDependencyAPI#gemspec
Gem::RequestSet::GemDependencyAPI#git
Gem::RequestSet::GemDependencyAPI#group
Gem::TestCase#git_gem
Gem::TestCase::SpecFetcherSetup#gem
Gem::Uninstaller#gem_home
Gem::Util::gunzip
Gem::Util::gzip
Gem::gunzip
Gem::gzip
GetoptLong#get
GetoptLong#get_option
IO#getbyte
IO#getc
IO#getch
IO#gets
IO::generic_readable#getch
IPSocket#getaddress
IPSocket::getaddress
IPSocket::getaddress_orig
IRB::FileInputMethod#gets
IRB::InputMethod#gets
IRB::Locale#gets
IRB::ReadlineInputMethod#gets
IRB::StdioInputMethod#gets
Integer#gcd
Integer#gcdlcm
JSON#generate
JSON::generator
Kconv#guess
Kconv::guess
Kernel#gem
Kernel#gem_original_require
Kernel#gets
Kernel#global_variables
Kernel#gsub
Math::gamma
NKF::guess
Net::FTP#get
Net::FTP#getbinaryfile
Net::FTP#getdir
Net::FTP#gettextfile
Net::HTTP#get
Net::HTTP#get2
Net::HTTP::get
Net::HTTP::get_print
Net::HTTP::get_response
Net::HTTPHeader#get_fields
Net::IMAP#generate_tag
Net::IMAP#get_response
Net::IMAP#get_tagged_response
Net::IMAP#getacl
Net::IMAP#getquota
Net::IMAP#getquotaroot
Net::IMAP#greeting
Net::SMTP#get_response
Net::SMTP#getok
ObjectSpace::garbage_collect
OpenSSL::BN::generate_prime
OpenSSL::Buffering#getc
OpenSSL::Buffering#gets
OpenSSL::Config#get_definition
OpenSSL::Config#get_key_string
OpenSSL::Config#get_line
OpenSSL::Config#get_value
OpenSSL::PKey::DH#generate_key!
OpenSSL::PKey::DH::generate
OpenSSL::PKey::DSA::generate
OpenSSL::PKey::EC#generate_key
OpenSSL::PKey::EC#group
OpenSSL::PKey::EC#group=
OpenSSL::PKey::EC::Group#generator
OpenSSL::PKey::EC::Point#group
OpenSSL::PKey::RSA::generate
OptionParser#getopts
OptionParser::Arguable#getopts
OptionParser::Switch::guess
OptionParser::getopts
PP::PPMethods#guard_inspect_key
PTY::getpty
Pathname#grpowned?
Pathname::getwd
Pathname::glob
PrettyPrint#genspace
PrettyPrint#group
PrettyPrint#group_queue
PrettyPrint#group_sub
PrettyPrint::SingleLine#group
Prime::EratosthenesSieve#get_nth_prime
Process::GID::grant_privilege
Process::Sys::getegid
Process::Sys::geteuid
Process::Sys::getgid
Process::Sys::getuid
Process::UID::grant_privilege
Process::getpgid
Process::getpgrp
Process::getpriority
Process::getrlimit
Process::getsid
Process::gid
Process::gid=
Process::groups
Process::groups=
RDoc::Generator::Darkfish#gen_sub_directories
RDoc::Generator::Darkfish#generate
RDoc::Generator::Darkfish#generate_class
RDoc::Generator::Darkfish#generate_class_files
RDoc::Generator::Darkfish#generate_file_files
RDoc::Generator::Darkfish#generate_index
RDoc::Generator::Darkfish#generate_page
RDoc::Generator::Darkfish#generate_servlet_not_found
RDoc::Generator::Darkfish#generate_servlet_root
RDoc::Generator::Darkfish#generate_table_of_contents
RDoc::Generator::Darkfish#get_sorted_module_list
RDoc::Generator::Darkfish#get_svninfo
RDoc::Generator::JsonIndex#generate
RDoc::Generator::RI#generate
RDoc::Markdown#github
RDoc::Markup::Formatter::gen_relative_url
RDoc::Markup::Parser#get
RDoc::Markup::ToHtml#gen_url
RDoc::Markup::ToHtmlCrossref#gen_url
RDoc::Markup::ToHtmlSnippet#gen_url
RDoc::Markup::ToMarkdown#gen_url
RDoc::Options#generator
RDoc::Options#generator_descriptions
RDoc::Options#generator_options
RDoc::Parser::ChangeLog#group_entries
RDoc::Parser::Ruby#get_bool
RDoc::Parser::Ruby#get_class_or_module
RDoc::Parser::Ruby#get_class_specification
RDoc::Parser::Ruby#get_constant
RDoc::Parser::Ruby#get_constant_with_optional_parens
RDoc::Parser::Ruby#get_symbol_or_name
RDoc::Parser::RubyTools#get_tk
RDoc::Parser::RubyTools#get_tk_until
RDoc::Parser::RubyTools#get_tkread
RDoc::RD::BlockParser#get_included
RDoc::RDoc#gather_files
RDoc::RDoc#generate
RDoc::RDoc#generator
RDoc::RI::Paths::gem_dir
RDoc::RI::Paths::gemdirs
RDoc::RubygemsHook#generate
RDoc::RubygemsHook#generate_rdoc
RDoc::RubygemsHook#generate_ri
RDoc::RubygemsHook::generation_hook
RDoc::Servlet#generator_for
RDoc::Stats#great_job
RDoc::Task#generator
RDocTask#generator
REXML::Element#get_elements
REXML::Element#get_text
REXML::Functions::get_namespace
REXML::Parsers::SAX2Parser#get_listeners
REXML::Parsers::SAX2Parser#get_namespace
REXML::Parsers::SAX2Parser#get_procs
REXML::Parsers::XPathParser#get_group
REXML::Validation::State#generate_event
REXML::XPathParser#get_first
REXML::XPathParser#get_namespace
RSS::BaseListener#getter
RSS::Element#get_attributes
RSS::Maker::XMLStyleSheets::XMLStyleSheet#guess_type_if_need
RSS::Utils#get_file_and_line_from_caller
RSS::XMLStyleSheet#guess_type
Rake::Application#glob
Rake::FtpFile#group
Rake::TaskManager#generate_name
Rake::TaskManager#get_description
Readline::get_screen_size
Resolv#getaddress
Resolv#getaddresses
Resolv#getname
Resolv#getnames
Resolv::DNS#getaddress
Resolv::DNS#getaddresses
Resolv::DNS#getname
Resolv::DNS#getnames
Resolv::DNS#getresource
Resolv::DNS#getresources
Resolv::Hosts#getaddress
Resolv::Hosts#getaddresses
Resolv::Hosts#getname
Resolv::Hosts#getnames
Resolv::getaddress
Resolv::getaddresses
Resolv::getname
Resolv::getnames
Rinda::TupleEntry#get_renewer
Shell#getwd
Shell::CommandProcessor#glob
Socket::getaddrinfo
Socket::gethostbyaddr
Socket::gethostbyname
Socket::gethostname
Socket::getifaddrs
Socket::getnameinfo
Socket::getservbyname
Socket::getservbyport
String#getbyte
String#gsub
String#gsub!
StringIO#getbyte
StringIO#getc
StringIO#gets
StringScanner#get_byte
StringScanner#getbyte
StringScanner#getch
Symbol#gcd
Symbol#gcdlcm
TCPSocket::gethostbyname
Thread#group
Time#getgm
Time#getlocal
Time#getutc
Time#gmt?
Time#gmt_offset
Time#gmtime
Time#gmtoff
Time::gm
WEBrick::HTTPAuth::Htdigest#get_passwd
WEBrick::HTTPAuth::Htpasswd#get_passwd
WEBrick::HTTPAuth::UserDB#get_passwd
WEBrick::HTTPServlet::AbstractServlet::get_instance
WEBrick::Utils#getservername
WEBrick::Utils::getservername
WIN32OLE_TYPE#guid
WIN32OLE_TYPELIB#guid
XMLRPC::BasicServer#get_default_handler
XMLRPC::BasicServer#get_service_hook
XMLRPC::Client#gen_multicall
XMLRPC::Service::Interface#get_methods
XMLRPC::Service::PublicInstanceMethodsInterface#get_methods
XMLRPC::WEBrickServlet#get_instance
XMLRPC::WEBrickServlet#get_valid_ip
XMP::StringInputMethod#gets
Zlib::GzipReader#getbyte
Zlib::GzipReader#getc
Zlib::GzipReader#gets
